# Le score du theme 5 d'un user 1
GET http://localhost:3000/v1/api/students/1/themes/5/score
###


# Le score du theme 1 d'un user 6 - score 0
GET http://localhost:3000/v1/api/students/6/themes/1/score
###


# 404 - Le score du theme 700 d'un user 4 - THEME DO NOT EXIST
GET http://localhost:3000/v1/api/students/4/themes/700/score
###


# 404 - Le score du theme 700 d'un user 400 - USER DO NOT EXIST
GET http://localhost:3000/v1/api/students/400/themes/7/score
###


# Le score global d'un user 4
GET http://localhost:3000/v1/api/students/6/score
###

# Le score global d'un user 13
GET http://localhost:3000/v1/api/students/13/score
###


# Le score global d'un user 5
GET http://localhost:3000/v1/api/students/5/score
###


# Le score global d'un user 6
GET http://localhost:3000/v1/api/students/6/score
###



# 404 - Le score global d'un student 300 - STUDENT DO NOT EXISTS
GET http://localhost:3000/v1/api/students/300/score
###